import { Jogo } from "./game/Cena";
console.log("**************************************************");
console.log("* Contexo: Episódio Pete Festeiro, Apenas um Show*");
console.log("*                                                *");
console.log("* Benson decide tirar um dia de folga, então,    *");
console.log("* Mordecai e Rigby decidem fazer uma festa.      *");
console.log("* Eles organizam a festa com alguns refrigerantes*");
console.log("* antigos que encontraram no sótão. A festa não  *");
console.log("* se sai como o esperado, então eles decidem     *");
console.log("* chamar um mestre das festas: Pete Festeiro.    *");
console.log("* Pete vai ao parque, mas Mordecai e Rigby têm   *");
console.log("* dinheiro para pagar apenas 10 minutos de festa.*");
console.log("* Após os 10 minutos se passarem, Mordecai e     *");
console.log("* Rigby insistem para Pete ficar, oferecendo     *");
console.log("* como pagamento os refrigerantes antigos. Pete  *");
console.log("* aceita, e toma cada vez mais refrigerantes,    *");
console.log("* se tornando um tipo de deus da festa. Agora,   *");
console.log("* ele não quer mais parar a festa!               *");
console.log("*                                                *");
console.log("**************************************************");

const jogo = new Jogo();
jogo.iniciar();